In [1]:
#imports and scraping raw data from site
#df is the actual betting line
#df2 has other info, mostly using to get player id to name dict

import requests
from bs4 import BeautifulSoup as bs
import pandas as pd

pp_props_url = 'https://api.prizepicks.com/projections?league_id=7&per_page=250&single_stat=true'
headers = {
'Connection': 'keep-alive',
'Accept': 'application/json; charset=UTF-8',
'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36',
'Access-Control-Allow-Credentials': 'true',
'Sec-Fetch-Site': 'same-origin',
'Sec-Fetch-Mode': 'cors',
'Referer': 'https://app.prizepicks.com/',
'Accept-Encoding': 'gzip, deflate, br',
'Accept-Language': 'en-US,en;q=0.9'
}

r = requests.get(pp_props_url, headers=headers)
print(r)
df = pd.json_normalize(r.json()['data'])
df2 = pd.json_normalize(r.json()['included'])
print(df.loc[0])

C:\Users\User\anaconda3\lib\site-packages\requests\__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "

<Response [200]>
type                                                      projection
id                                                           1105437
attributes.board_time                      2023-02-27T20:10:08-05:00
attributes.custom_image                                         None
attributes.description                                           TOR
attributes.end_time                                             None
attributes.flash_sale_line_score                                None
attributes.is_promo                                            False
attributes.line_score                                            4.0
attributes.projection_type                               Single Stat
attributes.rank                                                    1
attributes.refundable                                           True
attributes.start_time                      2023-02-28T19:40:00-05:00
attributes.stat_type                                        Rebounds
attributes.status                                           pre_game
attributes.tv_channel                                           None
attributes.updated_at                      2023-02-27T20:12:32-05:00
relationships.duration.data                                     None
relationships.league.data.type                                league
relationships.league.data.id                                       7
relationships.new_player.data.type                        new_player
relationships.new_player.data.id                               54957
relationships.projection_type.data.type              projection_type
relationships.projection_type.data.id                              2
relationships.stat_type.data.type                          stat_type
relationships.stat_type.data.id                                   22
Name: 0, dtype: object

In [2]:
df2.drop(df2.columns[df2.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)

In [3]:
#getting names dict from df2

display(df2.head())
names = df2[['type','id', 'attributes.name']]
names = names.loc[names['type']=='new_player']
names = names[['id','attributes.name']]

name = names['attributes.name'].tolist()
id = names['id'].tolist()

names_dict = {id[i]: name[i] for i in range(len(name))}

#names_dict

,type,id,attributes.image_url,attributes.league,attributes.league_id,attributes.market,attributes.name,attributes.position,attributes.team,attributes.team_name,relationships.league.data.type,relationships.league.data.id,attributes.lfg_ignored_leagues,attributes.active,attributes.icon,attributes.last_five_games_enabled,attributes.projections_count,attributes.rank,relationships.projection_filters.data
0,new_player,37560,https://static.prizepicks.com/images/players/n...,NBA,7.0,Chicago,Nikola Vucevic,C,CHI,Bulls,league,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,new_player,54138,https://static.prizepicks.com/images/players/n...,NBA,7.0,Oklahoma City,Josh Giddey,G,OKC,Thunder,league,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,new_player,60019,https://static.prizepicks.com/images/players/n...,NBA,7.0,Indiana,Buddy Hield,G,IND,Pacers,league,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,new_player,1604,https://static.prizepicks.com/images/players/n...,NBA,7.0,Indiana,Myles Turner,C-F,IND,Pacers,league,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,new_player,87612,https://static.prizepicks.com/images/players/n...,NBA,7.0,San Antonio,Jeremy Sochan,F,SAS,Spurs,league,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.head()

,type,id,attributes.board_time,attributes.custom_image,attributes.description,attributes.end_time,attributes.flash_sale_line_score,attributes.is_promo,attributes.line_score,attributes.projection_type,...,attributes.updated_at,relationships.duration.data,relationships.league.data.type,relationships.league.data.id,relationships.new_player.data.type,relationships.new_player.data.id,relationships.projection_type.data.type,relationships.projection_type.data.id,relationships.stat_type.data.type,relationships.stat_type.data.id
0,projection,1105437,2023-02-27T20:10:08-05:00,None,TOR,None,None,False,4.0,Single Stat,...,2023-02-27T20:12:32-05:00,None,league,7,new_player,54957,projection_type,2,stat_type,22
1,projection,1105488,2023-02-27T20:10:08-05:00,None,TOR,None,None,False,9.5,Single Stat,...,2023-02-27T20:18:29-05:00,None,league,7,new_player,54957,projection_type,2,stat_type,245
2,projection,1105481,2023-02-27T20:10:08-05:00,None,TOR,None,None,False,28.5,Single Stat,...,2023-02-27T20:14:57-05:00,None,league,7,new_player,54957,projection_type,2,stat_type,244
3,projection,1105444,2023-02-27T20:10:08-05:00,None,TOR,None,None,False,5.0,Single Stat,...,2023-02-27T20:10:48-05:00,None,league,7,new_player,54957,projection_type,2,stat_type,20
4,projection,1105474,2023-02-27T20:10:08-05:00,None,TOR,None,None,False,27.5,Single Stat,...,2023-02-27T20:14:29-05:00,None,league,7,new_player,54957,projection_type,2,stat_type,243

In [5]:
#viewing all the columns to see what i need

base = df[:-1]
base.loc[63]

type                                                      projection
id                                                           1106130
attributes.board_time                      2023-02-27T23:08:00-05:00
attributes.custom_image                                         None
attributes.description                                           BKN
attributes.end_time                                             None
attributes.flash_sale_line_score                                None
attributes.is_promo                                            False
attributes.line_score                                            7.5
attributes.projection_type                               Single Stat
attributes.rank                                                  125
attributes.refundable                                           True
attributes.start_time                      2023-02-28T19:30:00-05:00
attributes.stat_type                                Free Throws Made
attributes.status                                           pre_game
attributes.tv_channel                                           None
attributes.updated_at                      2023-02-28T01:06:58-05:00
relationships.duration.data                                     None
relationships.league.data.type                                league
relationships.league.data.id                                       7
relationships.new_player.data.type                        new_player
relationships.new_player.data.id                               57720
relationships.projection_type.data.type              projection_type
relationships.projection_type.data.id                              2
relationships.stat_type.data.type                          stat_type
relationships.stat_type.data.id                                   68
Name: 63, dtype: object

In [6]:
id

['37560',
 '54138',
 '60019',
 '1604',
 '87612',
 '37655',
 '58307',
 '85747',
 '1738',
 '10772',
 '79868',
 '57212',
 '53829',
 '10731',
 '1521',
 '57720',
 '55140',
 '79925',
 '79861',
 '87498',
 '1381',
 '25107',
 '1544',
 '25419',
 '1724',
 '24935',
 '96540',
 '25422',
 '1957',
 '25447',
 '54044',
 '58731',
 '1291',
 '2023',
 '59971',
 '79926',
 '87384',
 '54957',
 '56700',
 '54811',
 '96521',
 '124403',
 '58812',
 '1629',
 '96236',
 '87695',
 '1973',
 '96502',
 '87590',
 '1390',
 '1683',
 '1382',
 '87508',
 '87403',
 '59729',
 '25099',
 '58830',
 '96508']

In [7]:
ids = df['relationships.new_player.data.id'].unique()
print(len(ids))
for i in ids[:-1]:
    print(names_dict[i],i)

58
DeMar DeRozan 54957
Fred VanVleet	 1973
Zach LaVine 1544
Pascal Siakam 57212
Nikola Vucevic 37560
Scottie Barnes 53829
Patrick Beverley 124403
Jakob Poeltl 96540
Coby White 10731
Gary Trent Jr. 37655
Patrick Williams 25422
Trae Young 1521
Bradley Beal 1381
John Collins 1390
Kyle Kuzma 58812
Bogdan Bogdanovic 25099
Giannis Antetokounmpo 57720
Mikal Bridges 96508
Jrue Holiday 25107
Spencer Dinwiddie 1957
Brook Lopez 1683
Anthony Davis 1382
Ja Morant 58307
Malik Beasley 96521
Desmond Bane 25447
Jarred Vanderbilt 96502
Jaren Jackson Jr. 10772
Dennis Schroder 24935
Dillon Brooks 1629
Santi Aldama 87508
Nikola Jokic 1291
Michael Porter Jr. 2023
Josh Giddey 54138
Tyrese Haliburton 59971
Luka Doncic 58830
Buddy Hield 60019
Kyrie Irving 96236
Myles Turner 1604
Aaron Nesmith 87498
Christian Wood 85747
Lauri Markkanen 79926
Kelly Olynyk 87403
Walker Kessler 79861
Talen Horton-Tucker 87695
Keldon Johnson 55140
Anthony Edwards 25419
Kawhi Leonard 1724
Jeremy Sochan 87612
Rudy Gobert 87384
Paul George 56700
Kyle Anderson 87590
Malaki Branham 79868
Norman Powell 59729
Damian Lillard 1738
Draymond Green 54811
Jerami Grant 79925
Jordan Poole 54044

In [8]:
#trimming excess columns and adding actual player names

df = base[['attributes.description','attributes.line_score',
        'attributes.stat_type','relationships.new_player.data.id']]

df['player_name'] = df['relationships.new_player.data.id'].map(names_dict)
df = df[['player_name','attributes.description', 'attributes.line_score', 'attributes.stat_type',
       'relationships.new_player.data.id']]

df = df.rename(columns={"attributes.description": "team", "attributes.line_score": "line", 
                        'attributes.stat_type':'stat','relationships.new_player.data.id':'id'})

C:\Users\User\AppData\Local\Temp\ipykernel_5024\1881028164.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['player_name'] = df['relationships.new_player.data.id'].map(names_dict)

In [9]:
df['player_name'].unique()

array(['DeMar DeRozan', 'Fred VanVleet\t', 'Zach LaVine', 'Pascal Siakam',
       'Nikola Vucevic', 'Scottie Barnes', 'Patrick Beverley',
       'Jakob Poeltl', 'Coby White', 'Gary Trent Jr.', 'Patrick Williams',
       'Trae Young', 'Bradley Beal', 'John Collins', 'Kyle Kuzma',
       'Bogdan Bogdanovic', 'Giannis Antetokounmpo', 'Mikal Bridges',
       'Jrue Holiday', 'Spencer Dinwiddie', 'Brook Lopez',
       'Anthony Davis', 'Ja Morant', 'Malik Beasley', 'Desmond Bane',
       'Jarred Vanderbilt', 'Jaren Jackson Jr.', 'Dennis Schroder',
       'Dillon Brooks', 'Santi Aldama', 'Nikola Jokic',
       'Michael Porter Jr.', 'Josh Giddey', 'Tyrese Haliburton',
       'Luka Doncic', 'Buddy Hield', 'Kyrie Irving', 'Myles Turner',
       'Aaron Nesmith', 'Christian Wood', 'Lauri Markkanen',
       'Kelly Olynyk', 'Walker Kessler', 'Talen Horton-Tucker',
       'Keldon Johnson', 'Anthony Edwards', 'Kawhi Leonard',
       'Jeremy Sochan', 'Rudy Gobert', 'Paul George', 'Kyle Anderson',
       'Malaki Branham', 'Norman Powell', 'Damian Lillard',
       'Draymond Green', 'Jerami Grant', 'Jordan Poole'], dtype=object)

In [10]:
df

        player_name team  line              stat     id
0     DeMar DeRozan  TOR   4.0          Rebounds  54957
1     DeMar DeRozan  TOR   9.5         Rebs+Asts  54957
2     DeMar DeRozan  TOR  28.5          Pts+Asts  54957
3     DeMar DeRozan  TOR   5.0           Assists  54957
4     DeMar DeRozan  TOR  27.5          Pts+Rebs  54957
..              ...  ...   ...               ...    ...
191   Norman Powell  MIN   3.5  Free Throws Made  59729
192  Damian Lillard  GSW   9.5  Free Throws Made   1738
193  Draymond Green  POR   0.5  Free Throws Made  54811
194    Jerami Grant  GSW   4.0  Free Throws Made  79925
195    Jordan Poole  POR   5.0  Free Throws Made  54044

[196 rows x 5 columns]

In [11]:
test = df
for i in range(len(test)):
    test.iloc[i,3] = test.iloc[i,3].replace('Points','PTS')
    test.iloc[i,3] = test.iloc[i,3].replace('Rebs','TRB')
    test.iloc[i,3] = test.iloc[i,3].replace('Asts','AST')
    test.iloc[i,3] = test.iloc[i,3].replace('Rebounds','TRB')
    test.iloc[i,3] = test.iloc[i,3].replace('3-PT Made','3P')
    test.iloc[i,3] = test.iloc[i,3].replace('Assists','AST')
    test.iloc[i,3] = test.iloc[i,3].replace('Turnovers','TOV')
    test.iloc[i,3] = test.iloc[i,3].replace('Blks','BLK')
    test.iloc[i,3] = test.iloc[i,3].replace('Pts','PTS')
    test.iloc[i,3] = test.iloc[i,3].replace('Stls','STL')
    test.iloc[i,3] = test.iloc[i,3].replace('Free Throws Made','FT')
    test.iloc[i,3] = test.iloc[i,3].replace('Blocked Shots','BLK')
    test.iloc[i,3] = test.iloc[i,3].replace('Steals','STL')
df = test

In [12]:
df.replace('Lebron James\t', 'Lebron James')

        player_name team  line     stat     id
0     DeMar DeRozan  TOR   4.0      TRB  54957
1     DeMar DeRozan  TOR   9.5  TRB+AST  54957
2     DeMar DeRozan  TOR  28.5  PTS+AST  54957
3     DeMar DeRozan  TOR   5.0      AST  54957
4     DeMar DeRozan  TOR  27.5  PTS+TRB  54957
..              ...  ...   ...      ...    ...
191   Norman Powell  MIN   3.5       FT  59729
192  Damian Lillard  GSW   9.5       FT   1738
193  Draymond Green  POR   0.5       FT  54811
194    Jerami Grant  GSW   4.0       FT  79925
195    Jordan Poole  POR   5.0       FT  54044

[196 rows x 5 columns]

In [13]:
len(df)

196

In [14]:
df = df[df.stat != 'Fantasy Score']

In [15]:
df.to_csv('betting_lines_8')

In [16]:
pd.option_context('display.max_columns', 50)
df

        player_name team  line     stat     id
0     DeMar DeRozan  TOR   4.0      TRB  54957
1     DeMar DeRozan  TOR   9.5  TRB+AST  54957
2     DeMar DeRozan  TOR  28.5  PTS+AST  54957
3     DeMar DeRozan  TOR   5.0      AST  54957
4     DeMar DeRozan  TOR  27.5  PTS+TRB  54957
..              ...  ...   ...      ...    ...
191   Norman Powell  MIN   3.5       FT  59729
192  Damian Lillard  GSW   9.5       FT   1738
193  Draymond Green  POR   0.5       FT  54811
194    Jerami Grant  GSW   4.0       FT  79925
195    Jordan Poole  POR   5.0       FT  54044

[196 rows x 5 columns]

In [17]:
if 'betting_lines_6' is_file():
    print(6)

SyntaxError: invalid syntax (2724057169.py, line 1)